os: linux
language: cpp
services:
  - docker
env:
  - PKG=fog05 VERSION=0.1.0 BRANCH=master
  - PKG=fog05-plugin-os-linux VERSION=0.1.0 BRANCH=master
  - PKG=fog05-plugin-net-linuxbridge VERSION=0.1.0 BRANCH=master
  - PKG=fog05-plugin-fdu-native VERSION=0.1.0 BRANCH=master
  - PKG=fog05-plugin-fdu-kvm VERSION=0.1.0 BRANCH=master
  - PKG=fog05-plugin-fdu-lxd VERSION=0.1.0 BRANCH=master
  - PKG=fog05-plugin-fdu-containerd VERSION=0.1.0 BRANCH=master
  - PKG=fog05-python3-sdk VERSION=0.1.0 BRANCH=0.1.x
  - PKG=fog05-python3-api VERSION=0.1.0 BRANCH=0.1.x
  - PKG=zenoh VERSION=0.1.0 BRANCH=0.3.0 IMAGE=fog05/debian-build:latest
  - PKG=libzenoh VERSION=0.1.0 BRANCH=0.3.0 IMAGE=debian:10-slim
script: bash -ex build_debs.sh